### PR TITLE
Readability for the amount of cards left in a filter for the PickCardsDialog

### PR DESCRIPTION
**Pull request by Celludriel**
As asked I'm opening this pull request on the test branch

At least I hope I'm , I usually work with SVN , GIT is still a bit strange to me

### CODE REVIEW

**Comment by kellyelton** [comment]
I'll need you to fill this out before I can accept this https://www.clahub.com/agreements/kellyelton/OCTGN

**Comment by kellyelton** [comment]
Actually before you sign, we have to make a few modifications

**Comment by kellyelton** [comment]
Ok you can sign now.

**Comment by kellyelton** [comment]
[rebuild]

**Comment by Celludriel** [comment]
All done , verify if it has been completed succesfully 

----- Original Message -----

**Pull request merged**
